CREATE TABLE score (
  id UUID NOT NULL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
  score FLOAT NOT NULL,
  game_name TEXT NOT NULL,
  user_id TEXT NOT NULL
);